### ISSUE TITLE
Error while calling public.powa_wait_sampling_src: canceling statement due to lock timeout

### ISSUE THREAD

**Issue by banlex73** [powa-team/powa#142] opened 2020-10-15 21:34 UTC
Getting Error while calling public.powa_wait_sampling_src: canceling statement due to lock timeout CONTEXT: PL/pgSQL function powa_wait_sampling_src(integer) line 4 at RETURN QUERYon.
Root cause: powa_wait_sampling extension on server blocks SELECT <>, * FROM public.powa_wait_sampling_src(0)
Cluster restart helps.

**Comment by rjuju** [comment] 2020-10-16 03:00
Hello,

> powa_wait_sampling extension on server blocks SELECT <>, * FROM public.powa_wait_sampling_src(0)

Do you mean pg_wait_sampling extension or something specific to powa_wait_sampling table?

This is likely a problem with pg_wait_sampling extension.  I think I already saw a similar problem using older versions of pg_wait_sampling extension.  Which version are you using?

If the problems reappears, could you show the full content of pg_stat_activity and pg_locks on the underlying remote server?

**Comment by banlex73** [comment] 2020-10-16 03:09
Hi Julien
I agree with you that it's rather *pg_wait_sampling *issue.
I am on the 1.1 version. Last January they released version 1.1.1 *, *So, I
have upgraded my dev environment today, hope it will fix the problem.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

чт, 15 жовт. 2020 о 20:01 Julien Rouhaud <notifications@github.com> пише:

**Comment by rjuju** [comment] 2021-01-07 14:28
Hello @banlex73.  For the record the problem is likely due to https://github.com/postgrespro/pg_wait_sampling/issues/29 (and https://github.com/postgrespro/pg_wait_sampling/issues/18)/  There's a PR to fix that at https://github.com/postgrespro/pg_wait_sampling/pull/31, so at we just have to wait to it to be merged and released.

**Comment by rjuju** [comment] 2021-03-08 14:05
As far as I can see this has been merged and released, so I'm closing this issue!

**Closed by rjuju** 2021-03-08 14:05 UTC
