### ISSUE TITLE
Does POWA work fine with EDB postgres?

### ISSUE THREAD

**Issue by manishnew09** [powa-team/powa#163] opened 2022-04-27 15:03 UTC
I have configured POWA on community edition of postgresql with version 13, It works absolutely fine. but when I did the same with EDB postgres, browser keeps crashing during navigation, or sometimes the click doesn't respond and then it crashes.
Hence would like to know if the latest verision is tested with EDB.

Thanks

**Comment by manishnew09** [comment] 2022-04-28 08:41
EDB Postgres 13 database itself is used as repository server, it a local mode

Setup details:

EDB postgres 13
Powa 	4.1.3
powa-web 4.1.3-1
hypopg 1.3.1
pg_qualstats 2.0.3
pg_stat_kcache 	2.2.0
pg_track_settings 2.0.1
pg_wait_sampling 1.1

I have license for EDB Postgres Enterprise edition.
I have also attached the browser utilization screenshot for referance
![Crome](https://user-images.githubusercontent.com/104429829/165711508-b8cf6f6a-e41d-45cb-8b01-f1a36a2025cb.PNG)

![Firefox](https://user-images.githubusercontent.com/104429829/165713383-ebff8af2-b9b6-4791-8199-730046b19059.PNG)

**Comment by rjuju** [comment] 2022-04-29 04:03
Thanks for providing the setup details!  I don't see anything unexpected there that would explain a different behavior base on the postgres server used.

On the screenshots do you only have a single tab with powa or a lot of other stuff?  The memory consumption is quite high, so I'm wondering if the problem is that on your EDB setup you have way more data stored.  It could be due to much more databases, higher pg_stat_statements.max, retention or snapshot frequency or things like that.

One thing you could try is to backup you powa database on EDB postgres and restore it on community postgres and see if this reproduces the problem.

**Comment by rjuju** [comment] 2022-04-29 08:18
> As recommended I have taken backup from powa database on EDB postgres and restored it on community postgres - this reproduced the problem.

Ah that makes more sense!

> Can you please help me to understand - what change should I make from above parameters to stop this issue from happening?

I see a few problematic settings that could explain your problem, which if I understand correctly is that the UI is retrieving some gigantic json blobs of data, exhausting your computer memory.

> pg_qualstats.sample_rate = 1

This one is definitely not recommended.  I'm assuming that you have a busy OLTP workload on your EDB postgres server, which doesn't play well with keeping track of all quals.  Unless this is a purely datawarehouse workload, this will lead to very high overhead due to concurrent locking.  In some case it can add up to 10% overhead, maybe more.

I see that you also limit the quals to 500, so it probably limit the memory footprint, but even so it's going to hurt your performance quite a lot for no benefit as most of the sampled quals are going to be evicted before the snapshot anyway.  You should probably use the default sample_rate setting (-1), which means 1/max_connections.  This make the overhead entirely disappear and should give you a representative overview of the quals.

> pg_qualstats.resolve_oids=true

This one also is clearly not recommended as it's *very* costly.  We never benchmarked it but it's likely to be around another 10% too.  You should disable it (requires a restart), as you can always resolve the oid manually if needed.  Note that the powa UI can also resolve the qual by connecting on the target database.


> pg_qualstats.track_pg_catalog=true

Unless you have specific issues with queries on the catalog there's no need to enable it.  It's not going to cost much, but a CPU cycle saved is always good, and since you limit the number of quals you might as well only keep more interesting quals.

> pg_quallstats.enabled=true

I'm assuming this is a typo and you have pg_qualstats not pg_quallstats written?

> powa.coalesce = 1000

This one seems quite high too.  This parameter is used to compress records when storing snapshots, and thus limiting the disk usage (you can refer to [this article](https://rjuju.github.io/postgresql/2016/09/16/minimizing-tuple-overhead.html) for more explanation on how it works if you're interesting), but with a value this high you probably won't gain a lot more on compression.  On the other hand, what will happen is that the *_current table are going to be quite bigger (maybe not a problem in local mode, as you have a data from a single server), but if you want to navigate in the UI on older data a single compressed row will contain more than 3 days of samples, that will then be processed by the UI.  All the graphs should limit the data to the interval specified, and to 100 points only, but maybe some parts of the UI are missing those checks which could lead to very high memory usage on your browser (and on the powa-web app).

**Comment by manishnew09** [comment] 2022-05-04 13:41
Thanks for the detailed explanation.
I will test it without the above parameters and let you know the results.

**Comment by manishnew09** [comment] 2022-05-09 06:24
Hello,
I have implemented POWA on EDB with all default parameters. Still the web pages for powa-web keeps crashing and after web page refresh it works fine for a few navigations and again it crashes. Also memory utilization of Crome and Firefox is slowing increases to 2MB to 3MB with only one tab open in it. So no change in the behavior. 
Any other recommendations that you can give for me to check further on this issue.

**Comment by rjuju** [comment] 2022-05-09 08:05
Did you mean 2 to 3 **GB** or **MB**?

Also, are you using the default interval visualization (1hour)?

Unfortunately without a way to reproduce the problem I can't do much.  Is there a way you could share a dump of a powa database that reproduces the issue?  The metrics themselves should not contain any sensitive data, **with the exception of pg_qualstats**.  pg_qualstats will store the constant values, thus potentially showing sensitive data.

If yes, what you could do as a first step is to uninstall pg_qualstats extension on the powa database.  It **won't remove the stored data**, but the UI won't try to access the related data anymore.  If the problem is still there, it means that a dump without pg_qualstats data (so without sensitive data) should be enough to diagnose the problem.  If the problem disappear, well at least I will know where to look.

**Comment by rjuju** [comment] 2022-05-09 08:18
I forgot to mention that you can then simply recreate pg_qualstats extension on the powa database and it will start aggregating the related data again.

**Comment by manishnew09** [comment] 2022-05-10 06:23
> Did you mean 2 to 3 **GB** or **MB**?
> Sorry, its 2 to 3 GB

> Also, are you using the default interval visualization (1hour)?
> Yes I am using default interval visualization for 1 hour.

> Unfortunately without a way to reproduce the problem I can't do much. Is there a way you could share a dump of a powa database that reproduces the issue? The metrics themselves should not contain any sensitive data, **with the exception of pg_qualstats**. pg_qualstats will store the constant values, thus potentially showing sensitive data.
> 
> If yes, what you could do as a first step is to uninstall pg_qualstats extension on the powa database. It **won't remove the stored data**, but the UI won't try to access the related data anymore. If the problem is still there, it means that a dump without pg_qualstats data (so without sensitive data) should be enough to diagnose the problem. If the problem disappear, well at least I will know where to look.
I would try the recommended steps and if the problem persists then, I will try to get you a dump.

**Comment by manishnew09** [comment] 2022-05-16 06:00
Hello,
I have attached the dump for "powa" database, as the issue still persists.
request you to please analyze and let me know if something is wrong.
[powa.zip](https://github.com/powa-team/powa/files/8697509/powa.zip)

**Comment by rjuju** [comment] 2022-05-16 07:31
Thanks!

So apparently the problems comes from pg_track_settings, which returns a 800kB json for a 1 hour interval.  Looking at the stored data, it seems that for some reason all the GUCs are detected as changed for each snapshot, which unsurprisingly leads to enormous amount of data.  The problem is mostly not parsing a 800kB json in the browser (although is surely doesn't help) but having d3.js adding all that information on each graph timeline.

Could you try to run this query, adapted from pg_track_settings, and see if it indeed returns every single GUC?

```
WITH src AS (
    SELECT * FROM public.pg_track_settings_settings_src(0)
), last_snapshot AS (
    SELECT srvid, name, setting
    FROM (
        SELECT srvid, name, setting,
          row_number() OVER (PARTITION BY NAME ORDER BY ts DESC) AS rownum
        FROM public.pg_track_settings_history h
        WHERE h.srvid = 0
    ) all_snapshots
    WHERE rownum = 1
)
select s.name src_name, l.name last_name, current_setting,
    s.setting src_setting, l.setting last_setting
from src s
left join last_snapshot l ON l.name = s.name WHERE (
    l.name IS NULL
    OR l.setting IS NOT DISTINCT FROM s.setting
);
```

If yes, either last_name should be NULL or src_setting should be different from last_setting, does it look like it's the case?

It's apparently not the case in your stored data:

```
# select count(*) from pg_track_settings_history ;
 count  
--------
 348596
(1 row)

# select name, count(distinct setting) from pg_track_settings_history group by 1 having count(distinct setting) > 1; 
 name | count 
------+-------
(0 rows)
```

I'm wondering if this is because EDB's version has different semantic for IS DISTINCT FROM.

**Comment by manishnew09** [comment] 2022-05-16 10:14
> WITH src AS (
>     SELECT * FROM public.pg_track_settings_settings_src(0)
> ), last_snapshot AS (
>     SELECT srvid, name, setting
>     FROM (
>         SELECT srvid, name, setting,
>           row_number() OVER (PARTITION BY NAME ORDER BY ts DESC) AS rownum
>         FROM public.pg_track_settings_history h
>         WHERE h.srvid = 0
>     ) all_snapshots
>     WHERE rownum = 1
> )
> select s.name src_name, l.name last_name, current_setting,
>     s.setting src_setting, l.setting last_setting
> from src s
> left join last_snapshot l ON l.name = s.name WHERE (
>     l.name IS NULL
>     OR l.setting IS NOT DISTINCT FROM s.setting
> );

Above SQL returned 404 rows. Almost all the settings are displayed..

**Comment by rjuju** [comment] 2022-05-16 10:22
Ah sorry I posted the wrong version of the query, it should be IS DISTINCT, not IS NOT DISTINCT, so:

```
WITH src AS (
    SELECT * FROM public.pg_track_settings_settings_src(0)
), last_snapshot AS (
    SELECT srvid, name, setting
    FROM (
        SELECT srvid, name, setting,
          row_number() OVER (PARTITION BY NAME ORDER BY ts DESC) AS rownum
        FROM public.pg_track_settings_history h
        WHERE h.srvid = 0
    ) all_snapshots
    WHERE rownum = 1
)
select s.name src_name, l.name last_name, current_setting,
    s.setting src_setting, l.setting last_setting
from src s
left join last_snapshot l ON l.name = s.name WHERE (
    l.name IS NULL
    OR l.setting IS DISTINCT FROM s.setting
);
```

**Comment by manishnew09** [comment] 2022-05-16 10:52
> WITH src AS (
>     SELECT * FROM public.pg_track_settings_settings_src(0)
> ), last_snapshot AS (
>     SELECT srvid, name, setting
>     FROM (
>         SELECT srvid, name, setting,
>           row_number() OVER (PARTITION BY NAME ORDER BY ts DESC) AS rownum
>         FROM public.pg_track_settings_history h
>         WHERE h.srvid = 0
>     ) all_snapshots
>     WHERE rownum = 1
> )
> select s.name src_name, l.name last_name, current_setting,
>     s.setting src_setting, l.setting last_setting
> from src s
> left join last_snapshot l ON l.name = s.name
> WHERE (
>     l.name IS NULL
>     OR l.setting IS DISTINCT FROM s.setting
> );

Output of the above query gives 403 rows, almost same.

**Comment by rjuju** [comment] 2022-05-16 13:33
Ok, so it seems that something is fishy with EDB postgres.  Do you know if there are some specific settings for oracle compatibility that may have some influence for this query?

What does this query returns?

```
SELECT current_setting('autovacuum'), current_setting('autovacuum') IS DISTINCT FROM 'on'::text, current_setting('autovacuum') IS DISTINCT FROM 'off'::text;
```

**Comment by rjuju** [comment] 2022-05-16 14:56
Thanks! Maybe a different behavior in the window function? Does the "last_snapshot" returns the full list of GUCs?

``` 
SELECT * FROM (
    SELECT srvid, name, setting,
    row_number() OVER (PARTITION BY NAME ORDER BY ts DESC) AS rownum
    FROM public.pg_track_settings_history h
    WHERE h.srvid = 0
) all_snapshots
WHERE rownum = 1;
```

**Comment by manishnew09** [comment] 2022-05-17 05:52
> Thanks! Maybe a different behavior in the window function? Does the "last_snapshot" returns the full list of GUCs?
> 
> ```
> SELECT * FROM (
>     SELECT srvid, name, setting,
>     row_number() OVER (PARTITION BY NAME ORDER BY ts DESC) AS rownum
>     FROM public.pg_track_settings_history h
>     WHERE h.srvid = 0
> ) all_snapshots
> WHERE rownum = 1;
> ```

Below is the outout for above query from my database:
 srvid |          name           | setting | rownum
-------+-------------------------+---------+--------
     0 | allow_system_table_mods | off     |      1
(1 row)


powa=# SELECT * FROM (
powa(#     SELECT srvid, name, setting,
powa(#     row_number() OVER (PARTITION BY NAME ORDER BY ts DESC) AS rownum
powa(#     FROM public.pg_track_settings_history h
powa(#     WHERE h.srvid = 0
powa(# ) last_snapshot
powa-# WHERE rownum = 1;
 srvid |          name           | setting | rownum
-------+-------------------------+---------+--------
     0 | allow_system_table_mods | off     |      1

**Comment by rjuju** [comment] 2022-05-17 06:22
Ok, so I have a totally different behavior on the restored dump on a vanilla postgres, here are the 10 first lines returned:

```
# SELECT * FROM (
    SELECT srvid, name, setting,
    row_number() OVER (PARTITION BY NAME ORDER BY ts DESC) AS rownum
    FROM public.pg_track_settings_history h
    WHERE h.srvid = 0
) all_snapshots
WHERE rownum = 1
LIMIT 10;
 srvid |              name               |                    setting                    | rownum 
-------+---------------------------------+-----------------------------------------------+--------
     0 | allow_system_table_mods         | off                                           |      1
     0 | application_name                | PoWA - pg_track_settings_snapshot_settings(0) |      1
     0 | archive_cleanup_command         |                                               |      1
     0 | archive_command                 | (disabled)                                    |      1
     0 | archive_mode                    | off                                           |      1
     0 | archive_timeout                 | 0                                             |      1
     0 | array_nulls                     | on                                            |      1
     0 | authentication_timeout          | 60                                            |      1
     0 | autovacuum                      | on                                            |      1
     0 | autovacuum_analyze_scale_factor | 0.1                                           |      1
(10 rows)
```

Unfortunately there's nothing I can do here if EDB postgres doesn't properly handle window functions, or row_number() specifically :(

You may ask EDB support if this is a know behavior and if yes if they have some configuration that can be set to bring back the normal behavior on a specific database (or role).  If not, I'm afraid that your only option is to remove pg_track_settings extension.

**Comment by rjuju** [comment] 2022-05-17 06:26
Oh, now that I think about it this may be a side effect of "rownum" being a thing in Oracle world, and maybe the fact that it's unqualified leads EDB parser to understand "global row number" rather than "all_snapshots.rownum".

Can you try this query instead?

```
SELECT * FROM (
    SELECT srvid, name, setting,
    row_number() OVER (PARTITION BY NAME ORDER BY ts DESC) AS rownum
    FROM public.pg_track_settings_history h
    WHERE h.srvid = 0
) all_snapshots
WHERE all_snapshots.rownum = 1
LIMIT 10;
```

If that fixes the query (ie. brings you 10 rows) that's definitely something I can fix in pg_track_settings, although arguably i don't think that "global rownum" should have precedence against an existing rownum attribute in the source relation.

**Comment by frost242** [comment] 2022-05-17 06:27
@rjuju : the rownum keyword is the problem here. Rownum is the painful way in Oracle to perform a LIMIT equivalent. By renaming the rownum alias to rn or anything else, the query works as expected.
```
# SELECT * FROM (
    SELECT srvid, name, setting,
    row_number() OVER (PARTITION BY NAME ORDER BY ts DESC) AS rn
    FROM public.pg_track_settings_history h
    WHERE h.srvid = 0
) all_snapshots
WHERE rn = 1
LIMIT 10;
 srvid |              name               |  setting   | rn
-------+---------------------------------+------------+----
     0 | allow_system_table_mods         | off        |  1
     0 | application_name                | psql.bin   |  1
     0 | archive_cleanup_command         |            |  1
     0 | archive_command                 | (disabled) |  1
     0 | archive_mode                    | off        |  1
     0 | archive_timeout                 | 0          |  1
     0 | array_nulls                     | on         |  1
     0 | authentication_timeout          | 60         |  1
     0 | autovacuum                      | on         |  1
     0 | autovacuum_analyze_scale_factor | 0.1        |  1
(10 lignes)
```

Also, the last query with `WHERE all_snapshots.rownum = 1` works flawlessly, just saw your update while writing this.

**Comment by rjuju** [comment] 2022-05-17 06:32
@frost242 yeah I just remembered about that after posting my first message.  I don't know which should have precedence, but in any case it's fixable for both vanilla postgres and EDB postgres without much effort so I will go ahead and do that.

Thanks a lot for the confirmation!

**Comment by frost242** [comment] 2022-05-17 06:36
I'll open a support ticket at EDB just in case it's a misbehavior. I remember seeing same kind of queries in an Oracle application and they won't perform correctly in EDB.
I'll let you know.

**Comment by manishnew09** [comment] 2022-05-17 06:37
> SELECT * FROM (
>     SELECT srvid, name, setting,
>     row_number() OVER (PARTITION BY NAME ORDER BY ts DESC) AS rownum
>     FROM public.pg_track_settings_history h
>     WHERE h.srvid = 0
> ) all_snapshots
> WHERE all_snapshots.rownum = 1
> LIMIT 10;


This gives me the output as below:

 srvid |              name               |                    setting                    | rownum
-------+---------------------------------+-----------------------------------------------+--------
     0 | allow_system_table_mods         | off                                           |      1
     0 | application_name                | PoWA - pg_track_settings_snapshot_settings(0) |      1
     0 | archive_cleanup_command         |                                               |      1
     0 | archive_command                 | (disabled)                                    |      1
     0 | archive_mode                    | off                                           |      1
     0 | archive_timeout                 | 0                                             |      1
     0 | array_nulls                     | on                                            |      1
     0 | authentication_timeout          | 60                                            |      1
     0 | autovacuum                      | on                                            |      1
     0 | autovacuum_analyze_scale_factor | 0.1                                           |      1
(10 rows)

**Comment by rjuju** [comment] 2022-05-17 07:02
Great, so this is clearly the problem.  Thanks all for the help!

I just pushed a fix at  https://github.com/rjuju/pg_track_settings/commit/11e702dda7f0a2845758972aa33aec995f47cef4.

@manishnew09 do you need a new release or can you try with the latest version directly from github?

**Comment by manishnew09** [comment] 2022-05-17 07:30
> Great, so this is clearly the problem. Thanks all for the help!
> 
> I just pushed a fix at [rjuju/pg_track_settings@11e702d](https://github.com/rjuju/pg_track_settings/commit/11e702dda7f0a2845758972aa33aec995f47cef4).
> 
> @manishnew09 do you need a new release or can you try with the latest version directly from github?

Thanks, I will try with the latest version directly from github and update you with the findings

**Comment by rjuju** [comment] 2022-05-17 07:57
Great!  You will have to drop the extension to clear all the data to make sure that you won't hit the same problem.

**Comment by frost242** [comment] 2022-05-17 13:20
Re, I looked back at the application queries I had in mind. The developer wrote "row_num" and not rownum. So there's no need to open a ticket at EDB... EDB seems to behave exactly like Oracle.

**Comment by manishnew09** [comment] 2022-05-20 06:33
Hello, 
I have tested powa with updated pg_track_setting extension, it is working perfectly fine now.
Thanks you so much for all the help.

Just one question not related to this, while configuring remote setup, what extensions can be activated on remote database server using  powa_activate_extension?

**Comment by rjuju** [comment] 2022-05-20 09:10
> I have tested powa with updated pg_track_setting extension, it is working perfectly fine now.

Great news!

> Just one question not related to this, while configuring remote setup, what extensions can be activated on remote database server using powa_activate_extension?

For now it's only the officially supported one, so:

1. powa, powa_stat_user_functions and powa_stat_all_relations
2. pg_stat_bgwriter
3. pg_stat_statements
4. pg_stat_kcache
5. pg_qualstats
6. pg_wait_sampling
7. pg_track_settings

Note that the first 3 in the list are automatically registered.  If you specify something unsupported the function will notify you by returning false.

**Comment by manishnew09** [comment] 2022-05-23 06:14
Thanks I will give it a try.

**Comment by manishnew09** [comment] 2022-05-23 11:40
Just tested it.
I think hypopg is not supported for remote server configurations? Any plans to add this extension feature in remote server configuration in future?

**Comment by rjuju** [comment] 2022-05-23 11:53
hypopg isn't a "stat extension", so you don't need to register it.  It's only used when the UI suggest new index: it dynamically checks if hypopg is installed, and if yes it will do an EXPLAIN with and without the suggested (hypothetical) index.

**Comment by rjuju** [comment] 2022-06-03 04:00
> Also there is a function powa_deactivate_server to deactivate a remote server, but is there a way to activate it again?

The "deactivation" is simply setting the frequency to -1, so all the data is kept as-is (no more snapshot, no purge of old data and so on).  So to activate it again would simply need to set some frequency.  I can add a dedicated function for that if you want, which would make things clearer?

**Closed** 2022-06-24 06:22 UTC
